# Generated by Django 5.0.4 on 2024-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_arttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_programtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programtype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
