# Generated by Django 5.0.6 on 2024-05-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_event',
        ),
    ]
