# Generated by Django 5.0.4 on 2024-04-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_arttype'),
        ('Guest', '0004_tbl_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artistwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_caption', models.CharField(max_length=50)),
                ('work_details', models.CharField(max_length=50)),
                ('work_image', models.FileField(upload_to='Work_Photo/')),
                ('work_price', models.CharField(max_length=50)),
                ('work_status', models.IntegerField(default=0)),
                ('work_date', models.DateField(auto_now_add=True)),
                ('artid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_artist')),
                ('arttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_arttype')),
            ],
        ),
    ]
