# Generated by Django 5.0.4 on 2024-04-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_artistwork',
            old_name='artid',
            new_name='artist',
        ),
    ]
