# Generated by Django 5.0.4 on 2024-05-01 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_programtype'),
        ('Artist', '0002_rename_artid_tbl_artistwork_artist'),
        ('Guest', '0004_tbl_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_artistprogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_caption', models.CharField(max_length=50)),
                ('program_details', models.CharField(max_length=50)),
                ('program_image', models.FileField(upload_to='Program_Photo/')),
                ('program_price', models.CharField(max_length=50)),
                ('program_status', models.IntegerField(default=0)),
                ('program_date', models.DateField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_artist')),
                ('programtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_programtype')),
            ],
        ),
    ]
