# Generated by Django 5.0.6 on 2024-05-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0003_tbl_artistprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_artistwork',
            name='work_stock',
            field=models.IntegerField(default=0),
        ),
    ]
