# Generated by Django 5.0.6 on 2024-05-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0004_tbl_artistwork_work_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_artistprogram',
            name='program_image',
            field=models.FileField(upload_to='Assets/Program_Photo/'),
        ),
        migrations.AlterField(
            model_name='tbl_artistwork',
            name='work_image',
            field=models.FileField(upload_to='Assets/Work_Photo/'),
        ),
        migrations.CreateModel(
            name='tbl_artistprogram_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_video', models.FileField(upload_to='Assets/Program_video/')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.tbl_artistprogram')),
            ],
        ),
    ]
