# Generated by Django 5.0.6 on 2024-05-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0006_tbl_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
    ]
