# Generated by Django 5.0.6 on 2024-05-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_artist'),
        ('User', '0006_remove_tbl_cart_booking_remove_tbl_cart_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
