# Generated by Django 5.0.6 on 2024-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_status',
            field=models.IntegerField(default='1'),
        ),
    ]
