# Generated by Django 5.0.6 on 2024-05-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_alter_tbl_user_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_artist',
            name='artist_gender',
        ),
    ]
