# Generated by Django 5.0.4 on 2024-04-23 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0002_rename_artid_tbl_artistwork_artist'),
        ('Guest', '0004_tbl_artist'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.IntegerField(default='0')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.tbl_artistwork')),
            ],
        ),
    ]
