# Generated by Django 5.0.4 on 2024-05-01 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist', '0003_tbl_artistprogram'),
        ('Guest', '0004_tbl_artist'),
        ('User', '0004_tbl_new_booking_tbl_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_programbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.IntegerField(default='0')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_fordate', models.DateField(null=True)),
                ('booking_description', models.CharField(max_length=50)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artist.tbl_artistprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
