# Generated by Django 5.0.6 on 2024-05-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_programbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_new_booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_programbooking',
            name='program',
        ),
        migrations.RemoveField(
            model_name='tbl_programbooking',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
        migrations.DeleteModel(
            name='tbl_new_booking',
        ),
        migrations.DeleteModel(
            name='tbl_programbooking',
        ),
    ]
