# Generated by Django 5.0.6 on 2024-05-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_ticket_booking_tbl_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_tickets',
            name='booking',
        ),
        migrations.DeleteModel(
            name='tbl_ticket_booking',
        ),
        migrations.DeleteModel(
            name='tbl_tickets',
        ),
    ]
